### ISSUE TITLE
do not submit .exe files to the repo

### ISSUE THREAD

**Issue by GWRon** [HenriVi/Editor#1]
I would suggest to create an .gitignore file in the root and ignore the *.exe files. Why? your exe file will be different on each little change - blowing up your repo (the full repo clone will be some megabytes more than needed).

**Comment by HenriVi** [comment]
Hi Ron,

I'm already ignoring *debug.exe and *.bmx/ . The release exe was a spur of a moment thing, but will probably let  go on next update.
